files from lesson_5
eugene-okulik/Agniia pull request #5
Opened 2024-02-08 21:39 UTC by AgataMalova

2024-02-09 09:26 UTC, eugene-okulik requested changes

2024-02-09 09:26 UTC, eugene-okulik commented on homework/Agniia_Sahin/lesson_5/task_2.py
> +index_result_1 = result_1.index('42')
Если мы еще при написании программы знаем, что там число 42, то можем просто написать `print(42 + 10)`.  
Идея в том, чтобы найти число в строках. Для этого нужно найти что-то одинаковое во всех строчках: количество символов перед числом разное; количество символов в числе разное; но в структуре всех строк есть что-то одинаковое.

2024-02-09 11:02 UTC, AgataMalova commented on homework/Agniia_Sahin/lesson_5/task_2.py
> +index_result_1 = result_1.index('42')
Были, конечно, сомнения, что неправильно делаю :/
То есть нужно создать 3 переменные, где именно эти числа получаются при помощи складывания, например двух чисел? Потом вывести результат с текстом и ее тоже сохранить в переменную,  и только потом уже находить с помощью индексов эти числа?
Тут общее то, что после : и пробела идут эти числа

2024-02-10 07:21 UTC, eugene-okulik commented on homework/Agniia_Sahin/lesson_5/task_2.py
> +index_result_1 = result_1.index('42')
Не очень понял последовательность, которую ты предлагаешь. Нужно:
1. Поместить эти 3 текста в три разные переменные (просто - руками)
2. В каждой переменной одинаковым кодом найти число (да, опираться на двоеточие - отличная идея) и сохранить каждое найденное число в отдельную переменную
3. к каждому числу приплюсовать 10 и распечатать результат.

2024-02-11 07:33 UTC, eugene-okulik approved these changes

2024-02-11 07:33 UTC, merged