Lesson 6
eugene-okulik/Agniia pull request #6
Opened 2024-02-15 12:03 UTC by AgataMalova

2024-02-15 12:45 UTC, AgataMalova commented
Не получается избавиться от ошибки blank line at end of file.

2024-02-16 09:40 UTC, eugene-okulik requested changes

2024-02-16 09:40 UTC, eugene-okulik commented on homework/Agniia_Sahin/lessoon_6/conditions_and_loops1.py
> +        fin_words.append(word[:-1] + 'ing' + word[-1])
👍

2024-02-16 09:40 UTC, eugene-okulik commented on homework/Agniia_Sahin/lessoon_6/conditions_and_loops2.py
> +        print(number)
Вместо числа 15 сейчас у тебя fuzz, а должно быть FuzzBuzz  
Решается это порядком условий. Помни - одно отработавшее условие исключает все следующие.

2024-02-17 10:53 UTC, eugene-okulik approved these changes

2024-02-17 10:53 UTC, merged