Files from lesson_8
eugene-okulik/Agniia pull request #8
Opened 2024-03-30 15:52 UTC by AgataMalova

Скажите, плис, что автотестирование это не как задача по фибоначи :D Это очень сложно

2024-03-31 16:06 UTC, eugene-okulik commented
> Скажите, плис, что автотестирование это не как задача по фибоначи :D Это очень сложно

Программирование в целом сложнее чем автотестирование. Автотестирование точно проще, но в программировании это первая тема из сложных. Еще будут декораторы и классы )))

2024-03-31 16:29 UTC, eugene-okulik requested changes

2024-03-31 16:29 UTC, eugene-okulik commented on homework/Agniia_Sahin/lesson_8/fibonacci.py
Фишка в том, что генератор - это такая функция, в которой есть ключевое слово yield. Здесь у тебя такого нет.  
Ну и заданием было создать генератор чисел фибоначчи, а потом из этого генератора получить пятое, двухсотое ну и так далее. А ты сделала функцию, которая вычисляет какое там число в фибоначчи будет на определенном месте.  
Последовательность фибоначчи это бесконечная последовательность, в которой первые два числа равны 0 и 1, а каждое последующее число равно сумме двух предыдущих чисел.  
то есть начало понятно 0, 1  
Следующее равно 0 + 1  - значит следующее тоже 1  
В этот момент результат 0, 1, 1
следующее равно 1 (последнее) + 1(предпоследнее)   - значит следующее 2
В этот момент результат 0, 1, 1, 2
следующее равно 2 (последнее) + 1(предпоследнее)   - значит следующее 3
В этот момент результат 0, 1, 1, 2, 3  
Ну и так далее. Генератор для этого будет выглядеть так
```python
def fibonacci():
    predposlednee = 0
    poslednee = 1
    while True:
        yield predposlednee
        old_predposlednee = predposlednee
        predposlednee = poslednee
        poslednee += old_predposlednee  # то же самое, что написать poslednee = poslednee + old_predposlednee
```
Более сжато, это можно написать так:
```python
def fibonacci():
    predposlednee, poslednee = 0, 1
    while True:
        yield predposlednee
        predposlednee, poslednee = poslednee, predposlednee + poslednee
```
Пользуемся результатом генератора мы с помощью цикла. И здесь это будет выглядеть так:
```python
count = 0
for number in fibonacci():
    count += 1
    if count == 5:
        print(number)
    elif count == 200:
        print(number)
        break
```
Если есть какие-то конкретные места, гед не понятно, пиши - будем разбираться.

2024-03-31 17:19 UTC, AgataMalova commented on homework/Agniia_Sahin/lesson_8/fibonacci.py
к этому коду остается добавить 1000 и 100000?
count = 0
for number in fibonacci():
    count += 1
    if count == 5:
        print(number)
    elif count == 200:
        print(number)
    elif count == 1000:
        print(number)
    elif count == 100000:
        print(number)
        break

2024-03-31 17:23 UTC, AgataMalova commented on homework/Agniia_Sahin/lesson_8/fibonacci.py
как сюда вставить код, чтобы все отступы и подсветка были?
у меня без отступов втсавляется

2024-03-31 17:26 UTC, eugene-okulik commented on homework/Agniia_Sahin/lesson_8/fibonacci.py
> как сюда вставить код, чтобы все отступы и подсветка были? у меня без отступов втсавляется

Я отредактировал твое сообщение. Можешь нажать для него edit и увидишь с помощью чего делается так, чтобы код вставлялся красивым.

2024-03-31 17:26 UTC, eugene-okulik commented on homework/Agniia_Sahin/lesson_8/fibonacci.py
> к этому коду остается добавить 1000 и 100000?
> 
> ```python
> count = 0
> for number in fibonacci():
>     count += 1
>     if count == 5:
>         print(number)
>     elif count == 200:
>         print(number)
>     elif count == 1000:
>         print(number)
>     elif count == 100000:
>         print(number)
>         break       
> ```

да

2024-04-04 09:02 UTC, eugene-okulik approved these changes

2024-04-04 09:02 UTC, merged